/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutComp: typeof import('./src/components/AboutComp.vue')['default']
    AdminCity: typeof import('./src/components/AdminCity.vue')['default']
    AdminIcon: typeof import('./src/components/icon/adminIcon.vue')['default']
    AdminPanel: typeof import('./src/components/AdminPanel.vue')['default']
    AdminRoute: typeof import('./src/components/AdminRoute.vue')['default']
    CityIcon: typeof import('./src/components/icon/cityIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    HomeComp: typeof import('./src/components/HomeComp.vue')['default']
    RouteIcon: typeof import('./src/components/icon/routeIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserComp: typeof import('./src/components/UserComp.vue')['default']
  }
}
